version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    container_name: eureka-server
    networks:
      - spring-net

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    container_name: user-service
    depends_on:
      - eureka-server
    networks:
      - spring-net

  name-service:
    build: ./name-service
    ports:
      - "8082:8082"
    container_name: name-service
    depends_on:
      - eureka-server
    networks:
      - spring-net

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    container_name: gateway-service
    depends_on:
      - eureka-server
      - user-service
      - name-service
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
